### ISSUE TITLE
Crash with Better Combat

### ISSUE THREAD

**Issue by GreenShaman** [KurodaAkira/RPG-Hud#13]
java.lang.NumberFormatException: For input string: "Attack"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at bettercombat.mod.main.GuiCrosshairsBC.renderAttackIndicator(GuiCrosshairsBC.java:91)
	at bettercombat.mod.main.BetterCombatEventHandler.onRenderGameOverlay(BetterCombatEventHandler.java:124)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_54_BetterCombatEventHandler_onRenderGameOverlay_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.pre(GuiIngameRPGHud.java:455)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.drawElement(GuiIngameRPGHud.java:626)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.func_175180_a(GuiIngameRPGHud.java:138)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1397)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

It's having trouble dealing with an attack indicator for the offhand.

**Comment by GreenShaman** [comment]
This issue never occurred in a previous version of the RPG-HUD mod from what I've experienced, it's likely to do with an oversight regarding the attack indicators.
