### ISSUE TITLE
Crash on world load (Unexpected error)

### ISSUE THREAD

**Issue by MoltenFury** [KurodaAkira/RPG-Hud#34]
Game version: 1.12.1. Trying load world or connect to the server, then game crashes ai getting this:
`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error`
Crash report:
---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 9/10/17 10:37 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.client.event.RenderGameOverlayEvent.<init>(RenderGameOverlayEvent.java:86)
	at net.minecraftforge.client.event.RenderGameOverlayEvent.<init>(RenderGameOverlayEvent.java:30)
	at net.minecraftforge.client.event.RenderGameOverlayEvent$Pre.<init>(RenderGameOverlayEvent.java:95)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:900)
	at net.minecraftforge.client.GuiIngameForge.func_180480_a(GuiIngameForge.java:254)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.func_175180_a(GuiIngameRPGHud.java:114)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1397)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.event.RenderGameOverlayEvent.<init>(RenderGameOverlayEvent.java:86)
	at net.minecraftforge.client.event.RenderGameOverlayEvent.<init>(RenderGameOverlayEvent.java:30)
	at net.minecraftforge.client.event.RenderGameOverlayEvent$Pre.<init>(RenderGameOverlayEvent.java:95)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:900)
	at net.minecraftforge.client.GuiIngameForge.func_180480_a(GuiIngameForge.java:254)
	at net.spellcraftgaming.lib.gui.override.GuiIngameRPGHud.func_175180_a(GuiIngameRPGHud.java:114)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['MoltenFury_'/376743, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Chunk stats: MultiplayerChunkCache: 0, 0
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1 game time, 1 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['MoltenFury_'/376743, l='MpServer', x=8.50, y=65.00, z=8.50]]
	Retry entities: 0 total; []
	Server brand: Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:426)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 186294720 bytes (177 MB) / 517021696 bytes (493 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.41 Powered by Forge 14.22.0.2474 Optifine OptiFine_1.12.1_HD_U_C5 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                       | Version      | Source                               | Signature                                |
	|:------ |:------------------------ |:------------ |:------------------------------------ |:---------------------------------------- |
	| UCHIJA | minecraft                | 1.12.1       | minecraft.jar                        | None                                     |
	| UCHIJA | mcp                      | 9.19         | minecraft.jar                        | None                                     |
	| UCHIJA | FML                      | 8.0.99.99    | forge-1.12.1-14.22.0.2474.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge                    | 14.22.0.2474 | forge-1.12.1-14.22.0.2474.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater        | 1.0          | MercuriusUpdater-1.12.1.jar          | None                                     |
	| UCHIJA | rpghud                   | 3.6.6        | [1.12] RPG-HUD-3.6.6.jar             | None                                     |
	| UCHIJA | yarrmateys_cutemobmodels | 1.0.16       | Cute-Mob-Models-Remake-Mod-1.12.jar  | None                                     |
	| UCHIJA | hud                      | 1.3.9        | hud-1.3.9-1.12.jar                   | None                                     |
	| UCHIJA | xaerominimap             | 1.13.6       | Xaeros_Minimap_1.13.6_Forge_1.12.jar | None                                     |
	| UCHIJA | xray                     | 1.3.3        | xray-1.12-1.3.3.jar                  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13474 Compatibility Profile Context 22.19.162.4' Renderer: 'AMD Radeon (TM) R7 370 Series'
	Launched Version: 1.12.1-forge1.12.1-14.22.0.2474
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R7 370 Series GL version 4.5.13474 Compatibility Profile Context 22.19.162.4, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-6500 APU with Radeon(tm) HD Graphics 
	OptiFine Version: OptiFine_1.12.1_HD_U_C5
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.13474 Compatibility Profile Context 22.19.162.4
	OpenGlRenderer: AMD Radeon (TM) R7 370 Series
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

This happens only on version 1.12.1, but i need only this version 😖
Tried to find a solution already in the finished topics, but could not.

**Comment by Raelzaryn** [comment]
This is really weird. I can't really find what's causing the error and on my end (tested it with 1.12.1) it works without problems. I'll try to see if one of the other mods causes it together.
Can you tell me what mods "hud" or "xray" are, so I can recreate this crash?

#Edit: The error seems to be with Forge 1.12.1 Seems I'll have to create a separate version for it.
For now please run forge-14.22.0.2470 instead of .2474. That way it'll run.

**Comment by MoltenFury** [comment]
I am here now, sorry for this long unactivity.
X-ray it's cheat mod for searching for valuable resources through textures. You can set it to any block and it will be visible through any obstacles. I use only as a last resort: D
Hud is another interface with a compass, frames with the health of enemies and just different useful functions. I'm using at the moment as an alternative to your mod.
I completely deleted the game, put the forge and only your mod, but it was exactly the same crash.
Okay, I'll try with another version of forge. I will write here about the result.

#Edit: Yeah, it works now. Thanks for help, it's amazing hud! :D

**Comment by Raelzaryn** [comment]
I'll get it to work with newer forge versions very soon.

#edit: which would be now. I actually had the time to look into it and uploaded a version to curse.
