### ISSUE TITLE
Incompatibility with Flexible Skills; Worlds crash on startup

### ISSUE THREAD

**Issue by ghost** [KurodaAkira/RPG-Hud#59]
Whenever I try to open a world with both RPGHud and Flexible Skills, the world will crash when attempting to spawn me in. Everything else works fine, (the game start ups properly, and the world loads smoothly, etc.) But when attempting to join, it results in a crash.

**Comment by Raelzaryn** [comment]
Please provide a crash log if possible. It contains a lot more information than you might think. The versions of the game and mods for example. As well as the code part causing the issue.

**Comment by ghost** [comment]
I tried to make a completely separate profile on the Twitch launcher with only Flexible Skills (flexible_skills-1.14.4-1.1.10.jar), and RPGHud ([1.14.4] RPG-HUD-3.6.9.3.jar), and the game refuses to start. The profile was completely fresh, so there wasn't anything on it at all. I had to try a new account because I couldn't find the original log, but since I haven't deleted them I'll keep looking to see if I find it. 
Here's the first log:

[14:52:22] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:52:23] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:52:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:52:23] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[14:52:23] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at C:\Users\Mikey\Twitch\Minecraft\Install\runtime\jre-x64
[14:52:23] [main/INFO]: Searching C:\Users\Mikey\Twitch\Minecraft\Instances\Crash Testing\mods for mods
[14:52:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:52:23] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:52:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:52:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:52:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:52:24] [main/FATAL]: There is a binary discrepancy between the expected input class aab (aab) and the actual class. Checksum on disk is d8b84339, in patch 840ab581. Things are probably about to go very wrong. Did you put something into the jar file?
[14:52:24] [main/FATAL]: FML is going to ignore this error, note that the patch will not be applied, and there is likely to be a malfunctioning behaviour, including not running at all
[14:52:24] [main/FATAL]: There is a binary discrepancy between the expected input class aac (aac) and the actual class. Checksum on disk is 84e05fcd, in patch 98dcbc. Things are probably about to go very wrong. Did you put something into the jar file?
[14:52:24] [main/FATAL]: FML is going to ignore this error, note that the patch will not be applied, and there is likely to be a malfunctioning behaviour, including not running at all
[14:52:24] [main/FATAL]: There is a binary discrepancy between the expected input class aaf (aaf) and the actual class. Checksum on disk is 4fb17cab, in patch ef1ee7de. Things are probably about to go very wrong. Did you put something into the jar file?
[14:52:24] [main/FATAL]: FML is going to ignore this error, note that the patch will not be applied, and there is likely to be a malfunctioning behaviour, including not running at all
[14:52:24] [main/FATAL]: Patcher expecting non-empty class data file for net.minecraft.entity.passive.EntityRabbit$AIAvoidEntity, but received empty.
[14:52:24] [main/ERROR]: Unable to launch
java.lang.RuntimeException: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.entity.passive.EntityRabbit$AIAvoidEntity, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:169) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.RuntimeException: Patcher expecting non-empty class data file for net.minecraft.entity.passive.EntityRabbit$AIAvoidEntity, but received empty, your vanilla jar may be corrupt.
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.applyPatch(ClassPatchManager.java:114) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.patcher.ClassPatchManager.getPatchedResource(ClassPatchManager.java:77) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.getFieldType(FMLDeobfuscatingRemapper.java:219) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.parseField(FMLDeobfuscatingRemapper.java:192) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.asm.transformers.deobf.FMLDeobfuscatingRemapper.setup(FMLDeobfuscatingRemapper.java:161) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.common.asm.FMLSanityChecker.injectData(FMLSanityChecker.java:187) ~[forge-1.12.2-14.23.5.2854.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:164) ~[forge-1.12.2-14.23.5.2854.jar:?]
	... 2 more
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Runtime.exit(Runtime.java:107)
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.System.exit(System.java:971)
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[14:52:24] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I not sure if this has anything to do with my computer and may just be a problem on my end as well.

**Comment by Raelzaryn** [comment]
Fixed with https://github.com/KurodaAkira/RPG-Hud/commit/a4ab3274a71d4dbb36b6e0d6f85ce79205a7a54d
Try the 3.6.9.4 version I uploaded just now. I changed the rendering base of the 1.14.4 version to the one used in 1.15.2 (event based) instead of the previous override one.

**Comment by ghost** [comment]
I just tried out the newest version, and it did fix the issue and now works. Thank you!

**Comment by Raelzaryn** [comment]
Np.
Let me know if there are any other issues.
