### ISSUE TITLE
Could not load 'plugins/[1.16.1]+RPG-HUD-3.7.jar' in folder 'plugins

### ISSUE THREAD

**Issue by GenesisIIX** [KurodaAkira/RPG-Hud#62]
I keep getting this error message on boot
[08:18:35 ERROR]: Could not load 'plugins/[1.16.1]+RPG-HUD-3.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-70]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-70]
        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-70]
        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-70]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-70]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-70]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 7 more

**Comment by Raelzaryn** [comment]
well. this is a client side forge mod, not a bukkit server plugin.
