### ISSUE TITLE
RPG Hud Class Loading Failure

### ISSUE THREAD

**Issue by DylinDK** [KurodaAkira/RPG-Hud#73]
[10:56:45] [main/FATAL] [ne.mi.fm.ModLoader/CORE]: Failed to initialize mod containers
net.minecraftforge.fml.ModLoadingException: RPG-Hud has class loading errors
?7java.lang.RuntimeException: Attempted to load class net/spellcraftgaming/rpghud/main/ModRPGHud for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:67) ~[forge:36.0] {re:classloading}
        at sun.reflect.GeneratedConstructorAccessor23.newInstance(Unknown Source) ~[?:?] {}
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.javafmlmod.FMLJavaModLanguageProvider$FMLModTarget.loadMod(FMLJavaModLanguageProvider.java:76) ~[forge:36.0] {re:classloading}
        at net.minecraftforge.fml.ModLoader.buildModContainerFromTOML(ModLoader.java:296) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$buildMods$29(ModLoader.java:275) ~[forge:?] {re:classloading}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.HashMap$EntrySpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.ModLoader.buildMods(ModLoader.java:277) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$11(ModLoader.java:177) ~[forge:?] {re:classloading}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_281] {}
        at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[forge:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:44) ~[forge:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.5-36.0.15.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.5-36.0.15.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.5-36.0.15.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.5-36.0.15.jar:?] {}
Caused by: java.lang.RuntimeException: Attempted to load class net/spellcraftgaming/rpghud/main/ModRPGHud for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:71) ~[forge-1.16.5-36.0.15.jar:36.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.0.9.jar:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.0.9.jar:?] {re:classloading}
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281] {}
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281] {}
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.<init>(FMLModContainer.java:61) ~[forge:36.0] {re:classloading}
        ... 39 more

**Comment by Raelzaryn** [comment]
This is a client side mod, don't install it on a server.

**Comment by DylinDK** [comment]
> This is a client-side mod, don't install it on a server.

Thank you, I can't believe I made a mistake like that. I appreciate your time.
